// <auto-generated />
using System;
using EleganceStudio.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EleganceStudio.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421004929_v3_4_ModelsUpdate")]
    partial class v3_4_ModelsUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EleganceStudio.API.Models.Barber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Barbers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            IsActive = true,
                            Name = "Edi",
                            Phone = "+351933320269"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            IsActive = true,
                            Name = "Tomas",
                            Phone = "+351914302079"
                        },
                        new
                        {
                            Id = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            IsActive = true,
                            Name = "Abreu",
                            Phone = "+351913388301"
                        });
                });

            modelBuilder.Entity("EleganceStudio.API.Models.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("BookingTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BarberId", "BookingDate", "BookingTime")
                        .IsUnique()
                        .HasFilter("\"Status\" != 'Cancelled' AND \"IsDeleted\" = false");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("EleganceStudio.API.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000001"),
                            DurationMinutes = 30,
                            Name = "Sobrancelhas",
                            Price = 3m
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000002"),
                            DurationMinutes = 30,
                            Name = "Barba",
                            Price = 6m
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000003"),
                            DurationMinutes = 30,
                            Name = "Corte Simples",
                            Price = 10m
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000004"),
                            DurationMinutes = 45,
                            Name = "Corte/Degradê",
                            Price = 15m
                        },
                        new
                        {
                            Id = new Guid("b2b2b2b2-0000-0000-0000-000000000005"),
                            DurationMinutes = 60,
                            Name = "Corte & Barba",
                            Price = 17m
                        });
                });

            modelBuilder.Entity("EleganceStudio.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BarberId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0c0c0c0-0000-0000-0000-000000000001"),
                            PasswordHash = "$2a$11$oyKzedD6ZP7BjWmY6UwdgOWKvvxkxZpviYPcz870wBi2.l6o7iebS",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("c0c0c0c0-0000-0000-0000-000000000002"),
                            BarberId = new Guid("a1a1a1a1-0000-0000-0000-000000000001"),
                            PasswordHash = "$2a$11$PeUUZSzXHjM6pPeEqAF6jeLPkX8dEjrQZHG13qCLmJ0RQFtYwefry",
                            Role = "Barber",
                            Username = "edi"
                        },
                        new
                        {
                            Id = new Guid("c0c0c0c0-0000-0000-0000-000000000003"),
                            BarberId = new Guid("a1a1a1a1-0000-0000-0000-000000000002"),
                            PasswordHash = "$2a$11$YL7DzsSWlKLX8wUGOXxBheM8NWIqKe3ZuXTxKyIQq1oq4v0WmUn5C",
                            Role = "Barber",
                            Username = "tomas"
                        },
                        new
                        {
                            Id = new Guid("c0c0c0c0-0000-0000-0000-000000000004"),
                            BarberId = new Guid("a1a1a1a1-0000-0000-0000-000000000003"),
                            PasswordHash = "$2a$11$9itTZu8gCgdNES8VvT5sAuUD/zH8eib3XXEuOE2MbDC6gLlcOpUZO",
                            Role = "Barber",
                            Username = "abreu"
                        });
                });

            modelBuilder.Entity("EleganceStudio.API.Models.Booking", b =>
                {
                    b.HasOne("EleganceStudio.API.Models.Barber", "Barber")
                        .WithMany("Bookings")
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EleganceStudio.API.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barber");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("EleganceStudio.API.Models.Barber", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
